//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliStokTakipDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Halilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Halilar()
        {
            this.Stoklar = new HashSet<Stoklar>();
            this.SiparisDetay = new HashSet<SiparisDetay>();
        }
    
        public int ID { get; set; }
        public int KategoriID { get; set; }
        public int MarkaID { get; set; }
        public int RenkID { get; set; }
        public int DesenID { get; set; }
        public int BoyutID { get; set; }
        public string BarkodNo { get; set; }
        public string HaliAdi { get; set; }
        public decimal Fiyat { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime UretimTarihi { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual Boyutlar Boyutlar { get; set; }
        public virtual Desenler Desenler { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Markalar Markalar { get; set; }
        public virtual Renkler Renkler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stoklar> Stoklar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
    }
}
