//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliStokTakipDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iadeler
    {
        public int ID { get; set; }
        public int SiparisID { get; set; }
        public System.DateTime IadeTarihi { get; set; }
        public string IadeNedeni { get; set; }
        public bool IadeOnayDurumu { get; set; }
    
        public virtual Siparisler Siparisler { get; set; }
    }
}
