//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliStokTakipDLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HaliStokTakipDBEntities : DbContext
    {
        public HaliStokTakipDBEntities()
            : base("name=HaliStokTakipDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boyutlar> Boyutlar { get; set; }
        public virtual DbSet<Desenler> Desenler { get; set; }
        public virtual DbSet<Halilar> Halilar { get; set; }
        public virtual DbSet<Iadeler> Iadeler { get; set; }
        public virtual DbSet<KargoTakip> KargoTakip { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Markalar> Markalar { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Notlar> Notlar { get; set; }
        public virtual DbSet<Renkler> Renkler { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<SiparisOdeme> SiparisOdeme { get; set; }
        public virtual DbSet<Stoklar> Stoklar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Yetkiler> Yetkiler { get; set; }
        public virtual DbSet<SiparisDetay> SiparisDetay { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<sp_BoyutListesi_Result> sp_BoyutListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BoyutListesi_Result>("sp_BoyutListesi");
        }
    
        public virtual ObjectResult<sp_DesenListesi_Result> sp_DesenListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DesenListesi_Result>("sp_DesenListesi");
        }
    
        public virtual ObjectResult<sp_HaliListesi_Result> sp_HaliListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HaliListesi_Result>("sp_HaliListesi");
        }
    
        public virtual ObjectResult<sp_IadeListesi_Result> sp_IadeListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_IadeListesi_Result>("sp_IadeListesi");
        }
    
        public virtual ObjectResult<sp_KargoListesi_Result> sp_KargoListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_KargoListesi_Result>("sp_KargoListesi");
        }
    
        public virtual ObjectResult<sp_KategoriListesi_Result> sp_KategoriListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_KategoriListesi_Result>("sp_KategoriListesi");
        }
    
        public virtual ObjectResult<sp_KullaniciListesi_Result> sp_KullaniciListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_KullaniciListesi_Result>("sp_KullaniciListesi");
        }
    
        public virtual ObjectResult<sp_MarkaListesi_Result> sp_MarkaListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MarkaListesi_Result>("sp_MarkaListesi");
        }
    
        public virtual ObjectResult<sp_MusteriListesi_Result> sp_MusteriListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MusteriListesi_Result>("sp_MusteriListesi");
        }
    
        public virtual ObjectResult<sp_NotListesi_Result> sp_NotListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_NotListesi_Result>("sp_NotListesi");
        }
    
        public virtual ObjectResult<sp_OdemeListesi_Result> sp_OdemeListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_OdemeListesi_Result>("sp_OdemeListesi");
        }
    
        public virtual ObjectResult<sp_RenkListesi_Result> sp_RenkListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RenkListesi_Result>("sp_RenkListesi");
        }
    
        public virtual ObjectResult<sp_SiparisListesi_Result> sp_SiparisListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SiparisListesi_Result>("sp_SiparisListesi");
        }
    
        public virtual ObjectResult<sp_StokListesi_Result> sp_StokListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_StokListesi_Result>("sp_StokListesi");
        }
    
        public virtual ObjectResult<sp_YetkiListesi_Result> sp_YetkiListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_YetkiListesi_Result>("sp_YetkiListesi");
        }
    }
}
