//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliStokTakipDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisDetay
    {
        public int SiparisID { get; set; }
        public int HaliID { get; set; }
        public bool AktifMi { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Halilar Halilar { get; set; }
        public virtual Siparisler Siparisler { get; set; }
    }
}
